version: '3.9'

name: hotel_reservation
services:

  psql:
    container_name: hotel_db
    image: postgres:15.4
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: hotel_db
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data: